@ECHO OFF 
CLS
REM
REM Mi primer fichero por lotes 
REM Línea de comentario
REM ESCRIBIR UN MENSAJE EN LA PANTALLA
ECHO HOLA
REM Escribir línea en blanco, únicamente poner ECHO
ECHO 
ECHO ADIOS
REM REALIZAR UNA PAUSA
PAUSE
ECHO HOLA OTRA VEZ
PAUSE
PAUSE > NUL
REM PARA LLAMAR A UN FICHERO POR LOTES UTILIZAREMOS EL COMANDO CALL
