@echo off
title Menu batch
cls
:MENU
cls
ECHO.
ECHO ====MENU BATCH JUAN MARIA ========
ECHO 0. SALIR DEL MENU
ECHO A. RECIBIR UN SALUDO
ECHO B. COMPROBAR SI USAS WINDOWS
ECHO C. SUMAR DOS NUMEROS
ECHO D. RESTAR DOS NUMEROS
ECHO E. ERES MAYOR DE EDAD?
ECHO F. ERES UN USUSARIO REGISTRADO?
ECHO G. ABRIR INTERNET EXPLORER
ECHO H. VER LA FECHA
ECHO I. VER LA HORA
ECHO J. VER TU NOMBRE DE USUARIO
ECHO.
ECHO ====MENU BATCH JUAN MARIA =======

CHOICE /C 0ABCDEFGHIJ /D 0 /T 20 

IF ERRORLEVEL 11 GOTO	:USERNAME
IF ERRORLEVEL 10 GOTO	:HORA
IF ERRORLEVEL 9 GOTO	:FECHA
IF ERRORLEVEL 8 GOTO	:IEXP
IF ERRORLEVEL 7 GOTO	:CMP
IF ERRORLEVEL 6 GOTO	:EDAD
IF ERRORLEVEL 5 GOTO	:RESTA
IF ERRORLEVEL 4 GOTO	:SUMA
IF ERRORLEVEL 3 GOTO	:WIN
IF ERRORLEVEL 2 GOTO	:SALUDO
IF ERRORLEVEL 1 GOTO	:FIN


:USERNAME
ECHO %USERNAME%
TIMEOUT /T 20
GOTO	:MENU


:HORA
ECHO SON LAS %TIME% 
TIMEOUT /T 20
GOTO	:MENU 

:FECHA
ECHO LA FECHA DE HOY ES %DATE%
TIMEOUT /T 20
GOTO	:MENU

:SUMA
SET /P NUM1=INTRODUCE UN NUMERO 
SET /P NUM2=INTRODUCE OTRO NUMERO 
SET /A SUMA=%NUM1%+%NUM2%
ECHO EL RESULTADO ES %SUMA%
TIMEOUT /T 20
GOTO	:MENU

:RESTA
SET /P NUM1=ESCRIBE UN NUMERO 
SET /P NUM2=ESCRIBE UN NUMERO 
SET /A RESTA= %NUM1%-%NUM2%
ECHO EL RESULTADO ES %RESTA% 
TIMEOUT /T 20
GOTO	MENU

:EDAD
echo Cual es tu edad?
SET /P m=
IF %m% GEQ 18 (
echo ERES MAYOR DE EDAD
) ELSE (
echo NO ERES MAYOR DE EDAD
)
TIMEOUT /T 20
GOTO	:MENU

:WIN
IF EXIST C:\Windows\System32\WinMetadata (
ECHO USAS WINDOWS) ELSE (
ECHO NO USAS WINDOWS)

TIMEOUT /T 20
GOTO	:MENU

:CMP
SET /P NOM1=INTRODUCE TU NOMBRE DE USUARIO 
IF /I %NOM1% EQU %USERNAME% (
ECHO %USERNAME% ERES UN USUARIO REGISTRADO
)ELSE (ECHO NO ERES UN USUARIO REGISTRADO
) 
TIMEOUT /T 20
GOTO	:MENU

:IEXP
START IEXPLORE.EXE 
TIMEOUT /T 20
GOTO	:MENU

:SALUDO
ECHO HOLA %USERNAME%
TIMEOUT /T 20
GOTO	:MENU





:FIN
CHOICE /M "ESTAS SEGURO DE QUE QUIERES SALIR"
IF ERRORLEVEL 2 GOTO	:MENU
IF ERRORLEVEL 1 GOTO	:EOF