@echo off
:INICIO
cls
ECHO ESTE ES MI PRIMER MENU EN CMD
ECHO.
ECHO ==================================
ECHO.
ECHO a. Abrir notepad
ECHO b. Abrir paint
ECHO c. Recibir un saludo
ECHO d. Ver la fecha
ECHO s. Salir
ECHO ==================================
CHOICE /C ABCDS /CS /T 30 /D S /M "ELIGE LA OPCION "
IF ERRORLEVEL 5 GOTO :EOF
IF ERRORLEVEL 4 GOTO :FECHA
IF ERRORLEVEL 3 GOTO :SALUDO
IF ERRORLEVEL 2 GOTO :PAINT
IF ERRORLEVEL 1 GOTO :NOTEPAD
GOTO :EOF
:FECHA
ECHO %DATE%
PAUSE
GOTO :INICIO
:PAINT
ECHO ABRIR EL PAINT
PAUSE
GOTO :INICIO
:SALUDO
ECHO HOLA
TIMEOUT /T 10
GOTO :INICIO
:NOTEPAD
ECHO ABRIR EL NOTEPAD
TIMEOUT /T 10
GOTO :INICIO