@echo off
title Menu batch
cls
:MENU
cls
ECHO.
ECHO ====MENU BATCH JUAN MARIA ========
ECHO 0. SALIR DEL MENU
ECHO 1. RECIBIR UN SALUDO
ECHO 2. COMPROBAR SI USAS WINDOWS
ECHO 3. SUMAR DOS NUMEROS
ECHO 4. RESTAR DOS NUMEROS
ECHO 5. ERES MAYOR DE EDAD?
ECHO 6. ERES UN USUSARIO REGISTRADO?
ECHO 7. ABRIR INTERNET EXPLORER
ECHO 8. VER LA FECHA
ECHO 9. VER LA HORA
ECHO 10. VER TU NOMBRE DE USUARIO
ECHO.
ECHO ====MENU BATCH JUAN MARIA =======

:CHOICE
SET /P OPCION=ELIGE 
IF %OPCION%==0 GOTO	:FIN
IF %OPCION%==1 GOTO	:SALUDO
IF %OPCION%==2 GOTO	:WIN
IF %OPCION%==3 GOTO	:SUMA
IF %OPCION%==4 GOTO	:RESTA
IF %OPCION%==5 GOTO	:EDAD
IF %OPCION%==6 GOTO	:CMP
IF %OPCION%==7 GOTO	:IEXP
IF %OPCION%==8 GOTO	:FECHA
IF %OPCION%==9 GOTO	:HORA

GOTO	:FIN

:HORA
ECHO SON LAS %TIME% 
TIMEOUT /T 20
GOTO	:MENU 

:FECHA
ECHO LA FECHA DE HOY ES %DATE%
TIMEOUT /T 20
GOTO	:MENU

:SUMA
SET /P NUM1=INTRODUCE UN NUMERO 
SET /P NUM2=INTRODUCE OTRO NUMERO 
SET /A SUMA=%NUM1%+%NUM2%
ECHO EL RESULTADO ES %SUMA%
TIMEOUT /T 20
GOTO	:MENU

:RESTA
SET /P NUM1=ESCRIBE UN NUMERO 
SET /P NUM2=ESCRIBE UN NUMERO 
SET /A RESTA= %NUM1%-%NUM2%
ECHO EL RESULTADO ES %RESTA% 
TIMEOUT /T 20
GOTO	MENU

:EDAD
echo Cual es tu edad?
SET /P m=
IF %m% GEQ 18 (
echo ERES MAYOR DE EDAD
) ELSE (
echo NO ERES MAYOR DE EDAD
)
TIMEOUT /T 20
GOTO	:MENU

:WIN
IF EXIST C:\Windows\System32\WinMetadata (
ECHO USAS WINDOWS) ELSE (
ECHO NO USAS WINDOWS)

TIMEOUT /T 20
GOTO	:MENU

:CMP
SET /P NOM1=INTRODUCE TU NOMBRE DE USUARIO
IF /I %NOM1% EQU %USERNAME% (
ECHO %USERNAME% ERES UN USUARIO REGISTRADO
)ELSE (ECHO NO ERES UN USUARIO REGISTRADO
) 
TIMEOUT /T 20
GOTO	:MENU

:IEXP
START IEXPLORE.EXE 
TIMEOUT /T 20
GOTO	:MENU

:SALUDO
ECHO HOLA %USERNAME%
TIMEOUT /T 20
GOTO	:MENU


:FIN
CHOICE /M "ESTAS SEGURO DE QUE QUIERES SALIR"
IF ERRORLEVEL 2 GOTO	:MENU
IF ERRORLEVEL 1 GOTO	:EOF